### ISSUE TITLE
"Missing Scripts.rvdata2 (RuntimeError)" when trying to use rvpacker on WSL (Ubuntu 18.04)

### ISSUE THREAD

**Issue by LOuroboros** [Solistra/rvpacker#12]
```ruby
lunos@DESKTOP-L0QLBJC:/mnt/c/Users/Lunos/Desktop/RRW$ rvpacker --action unpack --project /mnt/c/Users/Lunos/Desktop/Rvpacked_RRW --project-type ace
[DEPRECATION] The trollop gem has been renamed to optimist and will no longer be supported. Please switch to optimist as soon as possible.
Traceback (most recent call last):
        4: from /usr/local/bin/rvpacker:23:in `<main>'
        3: from /usr/local/bin/rvpacker:23:in `load'
        2: from /var/lib/gems/2.5.0/gems/rvpacker-1.2.0/bin/rvpacker:27:in `<top (required)>'
        1: from /var/lib/gems/2.5.0/gems/rvpacker-1.2.0/lib/RGSS/serialize.rb:374:in `serialize'
/var/lib/gems/2.5.0/gems/rvpacker-1.2.0/lib/RGSS/serialize.rb:175:in `scripts_to_text': Missing Scripts.rvdata2 (RuntimeError)
lunos@DESKTOP-L0QLBJC:/mnt/c/Users/Lunos/Desktop/RRW$
```

If I'm not misunderstanding, the problem is that the `scripts_to_text` parser can't find the `Scripts.rvdata2` file?
It's definitely present in the "Data" folder though.

**Comment by somebody1234** [comment]
you're supposed to pass the path to the game in `--project`; the current directory (?) should be where it's output

**Comment by LOuroboros** [comment]
> 
> 
> you're supposed to pass the path to the game in `--project`; the current directory (?) should be where it's output

Meaning that I should be trying to use a command such as this `rvpacker --action unpack --project /mnt/c/Users/Lunos/Desktop/RRW --project-type ace` *(RRW being the folder where the game's files are currently located)* while on WSL I browse the folder where I want the files generated by rvpacker to be in, is that correct?

I'll set things up again, as I uninstalled Ruby, the gems and stuff after posting this issue, and give it a shot again.

**Comment by somebody1234** [comment]
@LOuroboros (my bad, i've actually tried it now; it extracts in the same folder, to two new folders, `YAML` and `Scripts`. `pack` just moves from those two folders back into `Data` or whatever)

**Comment by LOuroboros** [comment]
> 
> 
> @LOuroboros (my bad, i've actually tried it now; it extracts in the same folder, to two new folders, `YAML` and `Scripts`. `pack` just moves from those two folders back into `Data` or whatever)

Ah, I see now. There's effectively a Scripts and a YAML folders in ---- after typing the following command: `rvpacker --action unpack --project "C:\Users\Lunos\Desktop\RRW" --project-type ace`.

Thank you very much!
