### ISSUE TITLE
Automate pack/unpack workflow as much as possible

### ISSUE THREAD

**Issue by akesterson** [Solistra/rvpacker#2]
Remembering to pack/unpack doesn't seem like a big deal to developers who are used to following build processes, but for designers/artists/musicians, this might lead to tripping over shoelaces more often than we want. Let's figure out a way to automate the workflow.

Criteria for Success
================

* Make changes in RPG Maker interface
 * Commit changes to version control, unpacking happens automatically
* Make changes outside of RPG Maker interface, commit
 * Pull changes to YAML files, Data/ directory automatically gets repacked on checkout

**Comment by Solistra** [comment]
Note: could potentially use something like `watchr`/`observr` for this (or some other way of polling for filesystem events).

**Comment by Solistra** [comment]
The more I think about this, the less I like the idea -- this really isn't the domain of `rvpacker` itself, it belongs to VCS hooks (for Git, you could use `pre-commit`, `pre-push`, and `post-merge` to handle most of this relatively seamlessly).

While an automated workflow would be a nice thing to have in `rvpacker`, I really feel like that isn't its purpose and will be closing this for now. (Perhaps some documentation on creating the appropriate hooks could be added at some point in the future, though.)
