### ISSUE TITLE
Assign rubygem owner to Solistra

### ISSUE THREAD

**Issue by akesterson** [Solistra/rvpacker#9]
Just filing this so it will fill my github inbox until I set you as the upstream owner of the [rubygem](https://rubygems.org/gems/rvpacker/versions/1.2.0)

**Comment by akesterson** [comment]
Also, the gemspec file needs to be updated to reflect the new ownership as well (emails, etc).

**Comment by Solistra** [comment]
I'll take the gemspec into account -- for now, I'm mostly waiting for the dust to settle before doing much work on rvpacker itself.

**Comment by akesterson** [comment]
Closing this issue since we have successfully moved the gem ownership to you
